/*
 * Copyright (C) 2013 Variscite Ltd. All Rights Reserved.
 * Maintainer: Uri Yosef <uri.y@variscite.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

#ifndef _BOARD_MX6Q_VAR_SOM_H
#define _BOARD_MX6Q_VAR_SOM_H
#include <mach/iomux-mx6q.h>

#define WLAN_IRQ_PADCFG  (PAD_CTL_PUE | PAD_CTL_PUS_100K_DOWN | PAD_CTL_SPEED_MED | PAD_CTL_DSE_40ohm | PAD_CTL_HYS)
#define WLAN_EN_PADCFG   (PAD_CTL_SPEED_MED | PAD_CTL_DSE_40ohm)

#define MX6Q_USDHC_PAD_SETTING(id, speed)	\
mx6q_sd##id##_##speed##mhz[] = {		\
	MX6Q_PAD_SD##id##_CLK__USDHC##id##_CLK_##speed##MHZ,	\
	MX6Q_PAD_SD##id##_CMD__USDHC##id##_CMD_##speed##MHZ,	\
	MX6Q_PAD_SD##id##_DAT0__USDHC##id##_DAT0_##speed##MHZ,	\
	MX6Q_PAD_SD##id##_DAT1__USDHC##id##_DAT1_##speed##MHZ,	\
	MX6Q_PAD_SD##id##_DAT2__USDHC##id##_DAT2_##speed##MHZ,	\
	MX6Q_PAD_SD##id##_DAT3__USDHC##id##_DAT3_##speed##MHZ,	\
}

static iomux_v3_cfg_t MX6Q_USDHC_PAD_SETTING(3, 50);
static iomux_v3_cfg_t MX6Q_USDHC_PAD_SETTING(3, 100);
static iomux_v3_cfg_t MX6Q_USDHC_PAD_SETTING(3, 200);

static iomux_v3_cfg_t mx6q_var_som_pads[] = {

	/* User Button */
	MX6Q_PAD_CSI0_DATA_EN__GPIO_5_20,

	/* Backlight PWM */
	MX6Q_PAD_DISP0_DAT9__PWM2_PWMO,

	/* CTW6120 IRQ */
	MX6Q_PAD_EIM_DA7__GPIO_3_7,

	/* Audio */
	MX6Q_PAD_GPIO_0__CCM_CLKO,
	
	/* AUDMUX */
	MX6Q_PAD_CSI0_DAT4__AUDMUX_AUD3_TXC,
	MX6Q_PAD_CSI0_DAT5__AUDMUX_AUD3_TXD,
	MX6Q_PAD_CSI0_DAT6__AUDMUX_AUD3_TXFS,
	MX6Q_PAD_CSI0_DAT7__AUDMUX_AUD3_RXD,

	/* SPI3 (ads7846) */
	MX6Q_PAD_DISP0_DAT2__ECSPI3_MISO,
	MX6Q_PAD_DISP0_DAT1__ECSPI3_MOSI,
	MX6Q_PAD_DISP0_DAT0__ECSPI3_SCLK,

	MX6Q_PAD_DISP0_DAT3__GPIO_4_24, /* touch panel CS */
	MX6Q_PAD_DISP0_DAT4__GPIO_4_25, /* touch panel irq */

	/* UART1 for debug */
	MX6Q_PAD_CSI0_DAT10__UART1_TXD,
	MX6Q_PAD_CSI0_DAT11__UART1_RXD,

	/* UART2 for for Bluetooth */
	MX6Q_PAD_EIM_D28__UART2_CTS,
	MX6Q_PAD_EIM_D29__UART2_RTS,
	MX6Q_PAD_SD3_DAT4__UART2_RXD,
	MX6Q_PAD_SD3_DAT5__UART2_TXD,

	/* UART3 for RS232 port */
	MX6Q_PAD_EIM_D23__UART3_CTS,
	MX6Q_PAD_EIM_EB3__UART3_RTS,
	MX6Q_PAD_EIM_D25__UART3_RXD,
	MX6Q_PAD_EIM_D24__UART3_TXD,

	/* Camera MCLK */
	MX6Q_PAD_GPIO_3__CCM_CLKO2,		
		
	/* SDMMC2 CD/WP */
	MX6Q_PAD_KEY_COL4__GPIO_4_14,
	MX6Q_PAD_KEY_ROW4__GPIO_4_15,
	
	/* USBOTG ID pin */
	MX6Q_PAD_GPIO_4__GPIO_1_4,

	/* USDHC2 */
	MX6Q_PAD_SD2_CLK__USDHC2_CLK,
	MX6Q_PAD_SD2_CMD__USDHC2_CMD,
	MX6Q_PAD_SD2_DAT0__USDHC2_DAT0,
	MX6Q_PAD_SD2_DAT1__USDHC2_DAT1,
	MX6Q_PAD_SD2_DAT2__USDHC2_DAT2,
	MX6Q_PAD_SD2_DAT3__USDHC2_DAT3,
	MX6Q_PAD_NANDF_D4__USDHC2_DAT4,
	MX6Q_PAD_NANDF_D5__USDHC2_DAT5,
	MX6Q_PAD_NANDF_D6__USDHC2_DAT6,
	MX6Q_PAD_NANDF_D7__USDHC2_DAT7,

	/* ENET */
	MX6Q_PAD_ENET_MDIO__ENET_MDIO,
	MX6Q_PAD_ENET_MDC__ENET_MDC,
	MX6Q_PAD_RGMII_TXC__ENET_RGMII_TXC,
	MX6Q_PAD_RGMII_TD0__ENET_RGMII_TD0,
	MX6Q_PAD_RGMII_TD1__ENET_RGMII_TD1,
	MX6Q_PAD_RGMII_TD2__ENET_RGMII_TD2,
	MX6Q_PAD_RGMII_TD3__ENET_RGMII_TD3,
	MX6Q_PAD_RGMII_TX_CTL__ENET_RGMII_TX_CTL,
	MX6Q_PAD_ENET_REF_CLK__ENET_TX_CLK,
	MX6Q_PAD_RGMII_RXC__ENET_RGMII_RXC,
	MX6Q_PAD_RGMII_RD0__ENET_RGMII_RD0,
	MX6Q_PAD_RGMII_RD1__ENET_RGMII_RD1,
	MX6Q_PAD_RGMII_RD2__ENET_RGMII_RD2,
	MX6Q_PAD_RGMII_RD3__ENET_RGMII_RD3,
	MX6Q_PAD_RGMII_RX_CTL__ENET_RGMII_RX_CTL,

	/* PMIC INT */
	MX6Q_PAD_GPIO_17__GPIO_7_12,

	/* I2C1 */
	MX6Q_PAD_CSI0_DAT8__I2C1_SDA,
	MX6Q_PAD_CSI0_DAT9__I2C1_SCL,

	/* I2C2 */
	MX6Q_PAD_KEY_COL3__I2C2_SCL,
	MX6Q_PAD_KEY_ROW3__I2C2_SDA,

	/* I2C3 */
	MX6Q_PAD_GPIO_16__I2C3_SDA,
	MX6Q_PAD_GPIO_5__I2C3_SCL,

	/* PCIE */
	MX6Q_PAD_EIM_D21__GPIO_3_21, /* PCIE_DIS */
	MX6Q_PAD_DISP0_DAT19__GPIO_5_13, /* PCIE_RST */
	MX6Q_PAD_SD4_DAT4__GPIO_2_12, /* PCIE_PWR_ENA */ 

	/* WLAN - USDHC3 */
	MX6Q_PAD_SD3_CMD__USDHC3_CMD_50MHZ,
	MX6Q_PAD_SD3_CLK__USDHC3_CLK_50MHZ,
	MX6Q_PAD_SD3_DAT0__USDHC3_DAT0_50MHZ,
	MX6Q_PAD_SD3_DAT1__USDHC3_DAT1_50MHZ,
	MX6Q_PAD_SD3_DAT2__USDHC3_DAT2_50MHZ,
	MX6Q_PAD_SD3_DAT3__USDHC3_DAT3_50MHZ,

	NEW_PAD_CTRL(MX6Q_PAD_SD3_DAT7__GPIO_6_17, WLAN_IRQ_PADCFG),  /* WLAN IRQ */
	NEW_PAD_CTRL(MX6Q_PAD_SD3_DAT6__GPIO_6_18, WLAN_EN_PADCFG),   /* BT_EN  */
	NEW_PAD_CTRL(MX6Q_PAD_SD3_RST__GPIO_7_8, WLAN_EN_PADCFG),     /* WL_EN */

	MX6Q_PAD_ENET_RXD0__OSC32K_32K_OUT, /* Slow clock */

	MX6Q_PAD_KEY_COL2__GPIO_4_10, /* camera reset */ 
	MX6Q_PAD_EIM_DA13__GPIO_3_13, /* camera power down */
};

static iomux_v3_cfg_t mx6q_gpmi_nand[] __initdata = {
	MX6Q_PAD_NANDF_CLE__RAWNAND_CLE,
	MX6Q_PAD_NANDF_ALE__RAWNAND_ALE,
	MX6Q_PAD_NANDF_CS0__RAWNAND_CE0N,
	MX6Q_PAD_NANDF_CS1__RAWNAND_CE1N,
	MX6Q_PAD_NANDF_RB0__RAWNAND_READY0,

	MX6Q_PAD_NANDF_D0__RAWNAND_D0,
	MX6Q_PAD_NANDF_D1__RAWNAND_D1,
	MX6Q_PAD_NANDF_D2__RAWNAND_D2,
	MX6Q_PAD_NANDF_D3__RAWNAND_D3,
	MX6Q_PAD_NANDF_D4__RAWNAND_D4,
	MX6Q_PAD_NANDF_D5__RAWNAND_D5,
	MX6Q_PAD_NANDF_D6__RAWNAND_D6,
	MX6Q_PAD_NANDF_D7__RAWNAND_D7,
	MX6Q_PAD_SD4_CMD__RAWNAND_RDN,
	MX6Q_PAD_SD4_CLK__RAWNAND_WRN,
	MX6Q_PAD_NANDF_WP_B__RAWNAND_RESETN,
};



static iomux_v3_cfg_t mx6q_var_som_hdmi_ddc_pads[] = {
	MX6Q_PAD_KEY_COL3__HDMI_TX_DDC_SCL, /* HDMI DDC SCL */
	MX6Q_PAD_KEY_ROW3__HDMI_TX_DDC_SDA, /* HDMI DDC SDA */
};

static iomux_v3_cfg_t mx6q_var_som_i2c2_pads[] = {
	MX6Q_PAD_KEY_COL3__I2C2_SCL,	/* I2C2 SCL */
	MX6Q_PAD_KEY_ROW3__I2C2_SDA,	/* I2C2 SDA */
};


#endif
